language: node_js
node_js:
  - "10"
  - "12"
  - "14"

os:
  - linux

cache:
  npm: false

script:
  - skip

branches:
  only:
    - gh-pages

install:
  - bundle install
  - npm install
  - npm ls @loopback/docs

before_deploy:
  - npm run build
  - npm run discovery-upload

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
  email: slnode@ca.ibm.com
  name: StrongLoop Bot
