name: Build PRs for LoopBack.io site

on:
  pull_request:
    branches:
      - gh-pages
  workflow_dispatch:
    branches:
      - gh-pages
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          persist-credentials: false

      - name: Use Node.js 16
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@52b8784594ec115fd17094752708121dc5dabb47 # v1.154.0
        with:
          ruby-version: 2.7

      - name: Install and Build ğŸ”§
        run: |
          bundle install
          npm install
          npm ls @loopback/docs 2>/dev/null || true
          npm run build
