name: Build and Deploy LoopBack.io site

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          persist-credentials: false

      - name: Use Node.js 18
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 18

      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@7bae1d00b5db9166f4f0fc47985a3a5702cb58f0 # v1.197.0
        with:
          ruby-version: 3.2

      - name: Install and Build ðŸ”§
        run: |
          bundle install
          npm install
          npm ls @loopback/docs 2>/dev/null || true
          npm run build
      
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@881db5376404c5c8d621010bcbec0310b58d5e29 # v4.6.8
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          branch: gh-pages
          folder: .
