name: Build and Deploy LoopBack.io site

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false

      - name: Use Node.js 18
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 18

      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@f321cf5a4d1533575411f8752cf25b86478b0442 # v1.193.0
        with:
          ruby-version: 3.2

      - name: Install and Build ðŸ”§
        run: |
          bundle install
          npm install
          npm ls @loopback/docs 2>/dev/null || true
          npm run build
      
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@920cbb300dcd3f0568dbc42700c61e2fd9e6139c # v4.6.4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          branch: gh-pages
          folder: .
